In [46]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7)

In [39]:
# load the dataset but only keep the top n words, zero the rest
#top_words = 5000
#(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)
X_train=numpy.array([ 
list([150,146,142,131,138,131,129,128,125,125,128,130,127]),
list([174,164,157,154,156,161,152,129,99,120,97,104,127,150,150,138,137,136,138,134,141,136,132,132,130]),
list([90,104,93,92,89,86,75,84,70,96]),
list([106,99,112,108,103,103,104,89,80,89,88,92,96,99,96,90,70,120,73]),
list([123,134,137,134,116,128,128,130,109,118,94,121,111]),
list([111,76,83,84,102,98,83,76,93,85,101,97,117]),
list([134,145,136,117,104,107,111,106,109,119]),
list([121,126,125,128,126,126,108,134,138,126,108,91,80,75,75,75,70,120,73]),
list([204,139,144,192,152,116,127,158,161,161,150,134,132,129,129,128,136,122,146,152,153,151]),
list([144,147,142,98,139,138,134,134,133,132,125,117,116,120,98,134,138,136,137,137,141,131]),
list([100,96,126,87,84,88,96,104,110,101,104,102,100,89,92,98]) 
])


y_train=numpy.array([1,1,1,1,1,1,1,1,0,0,0])

X_test=numpy.array([ 
list([133,139,143,150,156,159,119,151,131,104,99,99,103,124,140,146,145,112,142,142,137,139]),
list([112,115,111,109,106,106,94,114,88,86,92,99,104,91,91,93]),
list([108,113,93,116,98,104,93]),
list([130,121,118,113,113,113,116,116,118,123,129,123,119,123,125,126,123,119,123]),
list([98,82,77,85,92,101,112,121,141,134,141,134,106,85,71,73,72,125,73]) 
])

y_test=numpy.array([1,1,1,0,0])


In [40]:
# msp
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
print(X_test)
print(y_train)

(11,)
(11,)
(5,)
(5,)
[list([133, 139, 143, 150, 156, 159, 119, 151, 131, 104, 99, 99, 103, 124, 140, 146, 145, 112, 142, 142, 137, 139])
 list([112, 115, 111, 109, 106, 106, 94, 114, 88, 86, 92, 99, 104, 91, 91, 93])
 list([108, 113, 93, 116, 98, 104, 93])
 list([130, 121, 118, 113, 113, 113, 116, 116, 118, 123, 129, 123, 119, 123, 125, 126, 123, 119, 123])
 list([98, 82, 77, 85, 92, 101, 112, 121, 141, 134, 141, 134, 106, 85, 71, 73, 72, 125, 73])]
[1 1 1 1 1 1 1 1 0 0 0]


In [41]:
# truncate and pad input sequences
max_review_length = 25
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [42]:
# msp
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
print(X_test)
print(y_train)

(11, 25)
(11,)
(5, 25)
(5,)
[[  0   0   0 133 139 143 150 156 159 119 151 131 104  99  99 103 124 140
  146 145 112 142 142 137 139]
 [  0   0   0   0   0   0   0   0   0 112 115 111 109 106 106  94 114  88
   86  92  99 104  91  91  93]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  108 113  93 116  98 104  93]
 [  0   0   0   0   0   0 130 121 118 113 113 113 116 116 118 123 129 123
  119 123 125 126 123 119 123]
 [  0   0   0   0   0   0  98  82  77  85  92 101 112 121 141 134 141 134
  106  85  71  73  72 125  73]]
[1 1 1 1 1 1 1 1 0 0 0]


In [43]:
X_train=X_train.reshape(X_train.shape[0],X_train.shape[1],1)
X_test=X_test.reshape(X_test.shape[0],X_test.shape[1],1)
print(X_train.shape)
print(X_test.shape)
print(X_test)

(11, 25, 1)
(5, 25, 1)
[[[  0]
  [  0]
  [  0]
  [133]
  [139]
  [143]
  [150]
  [156]
  [159]
  [119]
  [151]
  [131]
  [104]
  [ 99]
  [ 99]
  [103]
  [124]
  [140]
  [146]
  [145]
  [112]
  [142]
  [142]
  [137]
  [139]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [112]
  [115]
  [111]
  [109]
  [106]
  [106]
  [ 94]
  [114]
  [ 88]
  [ 86]
  [ 92]
  [ 99]
  [104]
  [ 91]
  [ 91]
  [ 93]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [108]
  [113]
  [ 93]
  [116]
  [ 98]
  [104]
  [ 93]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [130]
  [121]
  [118]
  [113]
  [113]
  [113]
  [116]
  [116]
  [118]
  [123]
  [129]
  [123]
  [119]
  [123]
  [125]
  [126]
  [123]
  [119]
  [123]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 98]
  [ 82]
  [ 77]
  [ 85]
  [ 92]
  [101]
  [112]
  [121]
  [141]
  [134]
  [141]
  [134]
  [106]
  [ 85]
  [ 71]
 

In [44]:
# create the model
#embedding_vecor_length = 32
model = Sequential()
#model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(25,input_shape=(25,1)))#msp edit
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=6, batch_size=64)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_12 (LSTM)               (None, 25)                2700      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 26        
Total params: 2,726
Trainable params: 2,726
Non-trainable params: 0
_________________________________________________________________
None
Train on 11 samples, validate on 5 samples
Epoch 1/6
11/11 [==============================] - 1s 61ms/step - loss: 0.7915 - acc: 0.2727 - val_loss: 0.7383 - val_acc: 0.4000
Epoch 2/6
11/11 [==============================] - 0s 1ms/step - loss: 0.7824 - acc: 0.2727 - val_loss: 0.7336 - val_acc: 0.4000
Epoch 3/6
11/11 [==============================] - 0s 1ms/step - loss: 0.7747 - acc: 0.2727 - val_loss: 0.7297 - val_acc: 0.4000
Epoch 4/6
11/11 [==============================] - 0s 1ms/step - loss: 0.7680 - acc: 0.2727 - val_lo

In [45]:
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 40.00%
